Added customizing ColorPalette functionality
SarahHand/fractals pull request #21
Opened 2016-11-15 22:48 UTC by M00031

2016-11-15 22:59 UTC, SarahHand requested changes

2016-11-15 22:59 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/colorpalette/ChangeColorPalette.java
> +		positions.add(200);
What's 200?  Should it be COLOR_PALETTE_LENGTH?

2016-11-15 22:59 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/colorpalette/ColorPanel.java
> +		colorPosition = new JSlider(0, 200);
Again, what's 200? Should it be COLOR_PALETTE_LENGTH?

2016-11-15 22:59 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/colorpalette/ColorPanel.java
> +	int position = 100;
Why is this defaulted to 100? What is the significance of 100?

2016-11-15 23:18 UTC, M00031 commented on src/main/java/com/sarahhand/fractals/colorpalette/ColorPanel.java
> +	int position = 100;
It is defaulted to 100 because that is the middle of the slider length. I'll change it to COLOR_PALETTE_LENGTH / 2.

2016-11-15 23:28 UTC, SarahHand requested changes

2016-11-15 23:28 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/colorpalette/ChangeColorPalette.java
> +	private final int COLOR_PALETTE_LENGTH = 200;
Initialize this to ColorPalette.COLOR_PALETTE_LENGTH, or delete this, and just use ColorPalette.COLOR_PALETTE_LENGTH everywhere instead.

2016-11-16 19:45 UTC, SarahHand approved these changes
Looks good.

2016-11-16 19:46 UTC, merged