Screenshot functionality
SarahHand/fractals pull request #22
Opened 2016-11-16 20:10 UTC by M00031

2016-11-16 21:06 UTC, J9465812 requested changes

2016-11-16 21:06 UTC, J9465812 commented on src/main/java/com/sarahhand/fractals/view/FractalsUI.java
> +					ImageIO.write((BufferedImage)viewer.getView(frameDimension), "png", fileChooser.getSelectedFile());
You should add support for other image formats, like .jpg, .gif, and .bmp .

You can let the user choose the format and get the desired format name
from the last three letters in the name of the file.

2016-11-17 21:25 UTC, SarahHand requested changes

2016-11-17 21:25 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/view/FractalsUI.java
> +		List<String> extensions = Arrays.asList("png", "jpg", "jpeg", "bmp", "gif");
This variable can be made private.

2016-11-17 21:25 UTC, SarahHand commented on src/main/java/com/sarahhand/fractals/view/FractalsUI.java
> +	/** This class is the MouseListener for the frame. It is used for zooming in and out.
Update the comment to include panning.

2016-11-17 21:38 UTC, SarahHand approved these changes

2016-11-17 21:38 UTC, SarahHand approved these changes

2016-11-17 21:38 UTC, J9465812 approved these changes

2016-11-17 21:39 UTC, merged